# Generated by Django 5.0.6 on 2026-08-01 07:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('equipment_id', models.CharField(blank=True, default='', max_length=60)),
                ('range_spec', models.CharField(blank=True, default='', max_length=200)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('serial_no', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('calib_details', models.CharField(blank=True, default='', max_length=250)),
                ('calib_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Calibration Due', 'Calibration Due'), ('Under Maintenance', 'Under Maintenance'), ('Retired', 'Retired')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='labsettings',
            name='n_dch',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='n_dsp',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='pre_dch',
            field=models.CharField(default='ATS/DCH/', max_length=40),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='pre_dsp',
            field=models.CharField(default='ATS/DSP/', max_length=40),
        ),
        migrations.AddField(
            model_name='trf',
            name='batch_no',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='trf',
            name='op_end_image',
            field=models.FileField(blank=True, null=True, upload_to='test_images/'),
        ),
        migrations.AddField(
            model_name='trf',
            name='op_start_image',
            field=models.FileField(blank=True, null=True, upload_to='test_images/'),
        ),
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=60, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('client_name', models.CharField(max_length=160)),
                ('address', models.TextField(blank=True, default='')),
                ('trf_no', models.CharField(blank=True, default='', max_length=60)),
                ('report_no', models.CharField(blank=True, default='', max_length=80)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('courier', models.CharField(blank=True, default='', max_length=160)),
                ('created_by', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challans', to='core.trf')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('qty', models.CharField(blank=True, default='', max_length=40)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.challan')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=60, unique=True)),
                ('trf_no', models.CharField(blank=True, default='', max_length=60)),
                ('client_name', models.CharField(max_length=160)),
                ('courier_name', models.CharField(blank=True, default='', max_length=120)),
                ('tracking_no', models.CharField(blank=True, default='', max_length=120)),
                ('dispatch_date', models.DateField(default=django.utils.timezone.localdate)),
                ('sent_by', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='core.trf')),
            ],
            options={
                'verbose_name_plural': 'Dispatches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(blank=True, default='', max_length=160)),
                ('cert_no', models.CharField(max_length=80)),
                ('calib_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='calibration/')),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certs', to='core.equipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trf_no', models.CharField(blank=True, default='', max_length=60)),
                ('client_name', models.CharField(blank=True, default='', max_length=160)),
                ('report_no', models.CharField(max_length=80)),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('file', models.FileField(upload_to='lab_reports/')),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports', to='core.trf')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, default='', max_length=120)),
                ('organization', models.CharField(blank=True, default='', max_length=160)),
                ('trf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='core.trf')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
