# Generated by Django 5.0.6 on 2026-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dispatch_challan_prefixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='client_gst',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='challan',
            name='inv_ref',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='challan',
            name='other_info',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='challan',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challan',
            name='po_no',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='challan',
            name='purpose',
            field=models.CharField(blank=True, default='Sub-contracting', max_length=40),
        ),
    ]
