# Generated by Django 5.0.6 on 2026-08-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_challan_client_gst_challan_inv_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=20, unique=True)),
                ('company', models.CharField(max_length=160)),
                ('contact', models.CharField(blank=True, default='', max_length=80)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('state', models.CharField(blank=True, default='', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company'],
            },
        ),
        migrations.AddField(
            model_name='labsettings',
            name='num_pad',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='num_period',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='num_suffix',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='yearly_reset',
            field=models.BooleanField(default=False),
        ),
    ]
