# Generated by Django 5.0.6 on 2026-08-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_labsettings_num_pad_labsettings_num_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labsettings',
            name='num_suffix',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='pre_dch',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='pre_dsp',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='pre_ind',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='pre_inv',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='pre_ipo',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='pre_qtn',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='pre_trf',
        ),
        migrations.AddField(
            model_name='labsettings',
            name='code_dch',
            field=models.CharField(default='DCH', max_length=16),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='code_dsp',
            field=models.CharField(default='DSP', max_length=16),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='code_ind',
            field=models.CharField(default='IND', max_length=16),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='code_inv',
            field=models.CharField(default='INV', max_length=16),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='code_ipo',
            field=models.CharField(default='IPO', max_length=16),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='code_qtn',
            field=models.CharField(default='QTN', max_length=16),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='code_trf',
            field=models.CharField(default='TRF', max_length=16),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='num_format',
            field=models.CharField(default='{ORG}/{CODE}/{FY}/{NUM}', max_length=120),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='num_org',
            field=models.CharField(default='ATS', max_length=24),
        ),
    ]
